spring:
  application:
    name: service-order

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 50
          order_inserts: true
  server:
    port: 8080

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

    listener:
      simple:
        concurrency: 5
        max-concurrency: 20
        prefetch: 5

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: ${SPRING_DOC_SWAGGER_UI_PATH}
    config-url: /v3/api-docs/swagger-config
    url: ${SPRING_DOC_API_DOCS_PATH}
    display-request-duration: true
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - caches
          - loggers
          - mappings
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    rabbit:
      enabled: true
    redis:
      enabled: true
    metrics:
      enable:
        all: true
